### ISSUE TITLE
Multilingual support？

### ISSUE THREAD

**Issue by ghost** [nestquik/FOMOD-Creator#1]
can make a xml file to translate menu？

**Comment by amarf** [comment]
I will add the ability to do a translation for the program, but not multilanguage. I think within a few days I will find time for this work.
It's nice that this program is used. With a large number of users, I would start the new version of the program, but unfortunately the users are few.

**Comment by amarf** [comment]
Done.
Download: https://drive.google.com/open?id=0ByPAfTsdfcnCMXdCd1ozNVJBVUE

**Comment by ghost** [comment]
nice .modder is few ,modder using fo-tool is fewer. lol.
and pls check the "plugin"  item,it is with a prefix" key"..all the strings with "plugin" can not be localnized
http://imgur.com/pQrdyE6

**Comment by amarf** [comment]
Instead of "key: plugin-info": "MY TEXT", use "plugin-info": "MY TEXT"

**Comment by amarf** [comment]
If you want to add your language to the translations, just create a file in the Localize folder with your culture for example "Localizee.de.json" or "Localizee.zh.json" or "Localizee.zh-SG.json"
Program at startup add translation with a list of languages

**Comment by amarf** [comment]
OU! I ran the application and understood what the problem is.

**Comment by amarf** [comment]
Bug fixed.
Download v1.0.1 : https://drive.google.com/open?id=0ByPAfTsdfcnCMHplMmNVMm9jYVE
How to complete the translation, put the file here. I'll add it to the repositories. Thank you.

**Comment by ghost** [comment]
May  keep the item selected or highlight on left panel while it  is being edited on the right area?
Considering some fomod menu is very long ,hardly to find out which one  is  being edited if not highlight
Shown as pic  http://i.imgur.com/EaczJKB.gif

**Comment by amarf** [comment]
Done!
Download: https://drive.google.com/open?id=0ByPAfTsdfcnCSmxYeWxhZzFjTzA
