### ISSUE TITLE
condition value should be only  on/off?

### ISSUE THREAD

**Issue by ghost** [nestquik/FOMOD-Creator#2]
https://imgur.com/a/YOL7p
i can input string in value selector 1/3/4 ,is it  a bug or just  function for modder to define values beside on/off?
ps:this situation is also on  condition flags set item

**Comment by amarf** [comment]
I am not a developer of mods for Falaut4 and I do not know all editing rules. Nestquik (as co-developer and mod maker) decided to leave this field available for change.
If there are serious reasons to make this field with fixed values, then I will correct the program, but it will not be earlier than a week

**Comment by ghost** [comment]
ok，maybe nessary
